### ISSUE TITLE
Tried to TestApplication.java run multitenant-oauth2-spring-boot-starter, but when hitting url e.g. http://localhost:xxxx, not redirect to login page of keycloak

### ISSUE THREAD

**Issue by softwarepravin2007** [quantics-io/multitenant-oauth2-spring-boot-starter#8]
Used multitenant-oauth2-spring-boot-starter with keycloak. Added application.properties and also set default values as 
spring.security.oauth2.resourceserver.multitenant.enabled=true
spring.security.oauth2.resourceserver.resolve-mode=header
spring.security.oauth2.resourceserver.header.header-name=X-TENANT-ID

but still MultiTenantAuthenticationManagerResolver not executing.

**Comment by jomatt** [comment]
Hi @softwarepravin2007! Thanks for using our starter library and providing feedback. If I understand your issue correctly, you expect that the application automatically redirects you to a Keycloak login screen to authenticate if you open http://localhost:8080 in your browser.

A few notes:
- If you set up Keycloak, then you probably want to set `spring.security.oauth2.resourceserver.resolve-mode=jwt` in order to use the OAuth2 tokens from Keycloak. The `spring.security.oauth2.resourceserver.resolve-mode=header` property tells the library to extract the tenant from the HTTP request header `X-TENANT-ID` (this is meant to be used only for testing purposes but not with OAuth2). The `MultiTenantAuthenticationManagerResolver` is therefore only executed in JWT mode.
- The library does not contain a frontend so it will not redirect you to another URL if you hit http://localhost:8080 in your browser. However, if you add your own frontend, you can configure it to redirect unauthenticated users to the Keycloak login page (this is not part of this library).
- I suggest that you follow the following tutorial for configuring this library together with Keycloak: [How to make your multi-tenant Spring app production-ready](https://jomatt.io/how-to-make-your-multi-tenant-spring-app-production-ready/)

**Comment by softwarepravin2007** [comment]
Thanks Johannes Matt!!! This sample really helps me.

So I tested this sample as follows -
1. Added controller e.g. HelloController which exposes GET API as "/health"
2. Execute http://localhost:xxxx/health from Postman without JWT token in Bearer Authorization
3. Request fails with 401 error code i.e. Unauthorized.(This is expected behavior)
4. Generate JWT Token from keycloak API and set it as Bearer Authorization header during sending  http://localhost:xxxx/health 
5. Now got a response.(This is expected behavior)

Now my current need is -
1. In above step 4, automatically redirect to keycloak login page once hit "http://localhost:xxxx/health" for an unauthenticated user 
instead of generating tokens from keycloak API manually and set into  Bearer Authorization.
2. This sample is used Spring web(spring-boot-starter-web), I need to convert into reactive application (spring-boot-starter-webflux)
 
Could you please help me to resolve the above queries? I really stuck on and not able to do progress.

**Comment by jomatt** [comment]
> Now my current need is -
> 
> 1. In above step 4, automatically redirect to keycloak login page once hit "http://localhost:xxxx/health" for an unauthenticated user
>    instead of generating tokens from keycloak API manually and set into  Bearer Authorization.

For this, you would need to implement your own frontend and configure it to redirect unauthenticated users to the Keycloak login page (redirecting users is not part of this library since the library contains only backend code). If you just want to test the authentication flow using Keycloak, many REST API clients like Postman can show the login window in case your token is expired. You just need to tell Postman to use the auth URL and access token URL from your Keycloak realm.

> 2. This sample is used Spring web(spring-boot-starter-web), I need to convert into reactive application (spring-boot-starter-webflux)

The best way is to follow the official [Spring docs](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html).
